title: Bitcoin Cleanup
author:
  name: Bitcoin Cleanup
  email: hello@bitcoincleanup.com
description: > # this means to ignore newlines until "show_excerpts:"
  The Bitcoin Cleanup Blog
  
show_excerpts: false # set to true to show excerpts on the homepage

theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
