title: Bitcoin Cleanup
author: Bitcoin Cleanup
email: hello@bitcoincleanup.com
description: > # this means to ignore newlines until "show_excerpts:"
  The Bitcoin Cleanup Blog
  
show_excerpts: true

- blog/2022-09-22-greenpeace.md

theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
